"""Public structural contracts for pyqres.

Concrete reservoirs remain duck-typed. This package groups their stable
contracts by responsibility while preserving the original import surface.
"""

from .construction import (
    DynamicsInferenceProtocol,
    PresetRegistryProtocol,
    ReservoirBuilderProtocol,
    ReservoirCompilerProtocol,
    ReservoirFactoryProtocol,
    RunFunctionProtocol,
)
from .experiments import (
    DatasetProtocol,
    DatasetSplitProtocol,
    ExperimentProtocol,
    ExperimentResultProtocol,
    ReadoutProtocol,
    SupervisedDataBuilderProtocol,
    SweepProtocol,
    SweepResultProtocol,
    TaskDatasetFactoryProtocol,
    TaskRunnerProtocol,
    TimeSeriesDataBuilderProtocol,
)
from .reservoirs import (
    BatchReservoirProtocol,
    ChannelReservoirProtocol,
    CircuitReservoirProtocol,
    DimensionModelProtocol,
    MemoryObservableReservoirProtocol,
    QiskitReservoirConfigProtocol,
    QRCReservoirProtocol,
    QuantumCircuitProtocol,
    ReservoirRunResult,
    ReservoirStepResult,
    SparsePauliOpProtocol,
    StatefulReservoirProtocol,
    StepReservoirProtocol,
    StreamingReservoirProtocol,
    TransformReservoirProtocol,
)
from .specifications import (
    DynamicsSpecProtocol,
    HamiltonianSpecProtocol,
    InputEncodingSpecProtocol,
    ReadoutSpecProtocol,
    ReservoirSpecProtocol,
    SerializableSpecProtocol,
)
from .types import (
    BackendLike,
    CircuitLike,
    ConfigMapping,
    DynamicsLike,
    FeatureMatrix,
    HamiltonianLike,
    IndexSequence,
    InputSequence,
    MetricCallable,
    ObservableSpec,
    PauliTermLike,
    QiskitArtifactMap,
    TargetArray,
)

__all__ = [
    "BackendLike",
    "BatchReservoirProtocol",
    "ChannelReservoirProtocol",
    "CircuitLike",
    "CircuitReservoirProtocol",
    "ConfigMapping",
    "DatasetProtocol",
    "DatasetSplitProtocol",
    "DimensionModelProtocol",
    "DynamicsInferenceProtocol",
    "DynamicsLike",
    "DynamicsSpecProtocol",
    "ExperimentProtocol",
    "ExperimentResultProtocol",
    "FeatureMatrix",
    "HamiltonianLike",
    "HamiltonianSpecProtocol",
    "IndexSequence",
    "InputEncodingSpecProtocol",
    "InputSequence",
    "MemoryObservableReservoirProtocol",
    "MetricCallable",
    "ObservableSpec",
    "PauliTermLike",
    "PresetRegistryProtocol",
    "QRCReservoirProtocol",
    "QiskitArtifactMap",
    "QiskitReservoirConfigProtocol",
    "QuantumCircuitProtocol",
    "ReadoutProtocol",
    "ReadoutSpecProtocol",
    "ReservoirBuilderProtocol",
    "ReservoirCompilerProtocol",
    "ReservoirFactoryProtocol",
    "ReservoirRunResult",
    "ReservoirSpecProtocol",
    "ReservoirStepResult",
    "RunFunctionProtocol",
    "SerializableSpecProtocol",
    "SparsePauliOpProtocol",
    "StatefulReservoirProtocol",
    "StepReservoirProtocol",
    "StreamingReservoirProtocol",
    "SupervisedDataBuilderProtocol",
    "SweepProtocol",
    "SweepResultProtocol",
    "TargetArray",
    "TaskDatasetFactoryProtocol",
    "TaskRunnerProtocol",
    "TimeSeriesDataBuilderProtocol",
    "TransformReservoirProtocol",
]

_PUBLIC_CLASSES = (
    BatchReservoirProtocol,
    ChannelReservoirProtocol,
    CircuitReservoirProtocol,
    DatasetProtocol,
    DatasetSplitProtocol,
    DimensionModelProtocol,
    DynamicsInferenceProtocol,
    DynamicsSpecProtocol,
    ExperimentProtocol,
    ExperimentResultProtocol,
    HamiltonianSpecProtocol,
    InputEncodingSpecProtocol,
    MemoryObservableReservoirProtocol,
    PresetRegistryProtocol,
    QiskitReservoirConfigProtocol,
    QRCReservoirProtocol,
    QuantumCircuitProtocol,
    ReadoutProtocol,
    ReadoutSpecProtocol,
    ReservoirBuilderProtocol,
    ReservoirCompilerProtocol,
    ReservoirFactoryProtocol,
    ReservoirRunResult,
    ReservoirSpecProtocol,
    ReservoirStepResult,
    RunFunctionProtocol,
    SerializableSpecProtocol,
    SparsePauliOpProtocol,
    StatefulReservoirProtocol,
    StepReservoirProtocol,
    StreamingReservoirProtocol,
    SupervisedDataBuilderProtocol,
    SweepProtocol,
    SweepResultProtocol,
    TaskDatasetFactoryProtocol,
    TaskRunnerProtocol,
    TimeSeriesDataBuilderProtocol,
    TransformReservoirProtocol,
)

for _public_class in _PUBLIC_CLASSES:
    _public_class.__module__ = __name__

del _public_class
