"""Unified namespace for task-agnostic quantum reservoir computing tools."""

from . import presets
from .core import (
    BackendLike,
    BatchReservoirProtocol,
    ChannelReservoirProtocol,
    CircuitLike,
    CircuitReservoirProtocol,
    ConfigMapping,
    DatasetProtocol,
    DatasetSplitProtocol,
    DimensionModelProtocol,
    DynamicsInferenceProtocol,
    DynamicsLike,
    DynamicsSpecProtocol,
    ExperimentProtocol,
    ExperimentResultProtocol,
    FeatureMatrix,
    HamiltonianLike,
    HamiltonianSpecProtocol,
    IndexSequence,
    InputEncodingSpecProtocol,
    InputSequence,
    MemoryObservableReservoirProtocol,
    MetricCallable,
    ObservableSpec,
    PauliTermLike,
    PresetRegistryProtocol,
    QiskitArtifactMap,
    QiskitReservoirConfigProtocol,
    QRCReservoirProtocol,
    QuantumCircuitProtocol,
    ReadoutProtocol,
    ReadoutSpecProtocol,
    ReservoirBuilderProtocol,
    ReservoirCompilerProtocol,
    ReservoirFactoryProtocol,
    ReservoirRunResult,
    ReservoirSpecProtocol,
    ReservoirStepResult,
    RunFunctionProtocol,
    SerializableSpecProtocol,
    SparsePauliOpProtocol,
    StatefulReservoirProtocol,
    StepReservoirProtocol,
    StreamingReservoirProtocol,
    SupervisedDataBuilderProtocol,
    SweepProtocol,
    SweepResultProtocol,
    TargetArray,
    TaskDatasetFactoryProtocol,
    TaskRunnerProtocol,
    TimeSeriesDataBuilderProtocol,
    TransformReservoirProtocol,
)
from .core.builders import (
    build_dimension_model,
    build_hamiltonian_params,
    build_qiskit_hamiltonian_artifacts,
    compile_reservoir,
    run,
)
from .core.factory import qresreservoir
from .core.specs import DynamicsSpec, InputEncodingSpec, ReadoutSpec, ReservoirSpec
from .experiments import data, readout
from .experiments.datasets import Dataset, DatasetSplit
from .experiments.readout import Ridge
from .experiments.runner import Experiment, ExperimentResult, Sweep, SweepResult
from .prethermal_shadow import (
    GlobalFloquetConfig,
    GlobalFloquetPartialShadowReservoir,
    PartialShadowReadoutConfig,
    PrethermalCircuitConfig,
    PrethermalShadowDimensionModel,
    QiskitGlobalFloquetPartialShadowReservoir,
    ReadoutResetConfig,
)
from .prethermal_shadow import InputEncodingConfig as PrethermalInputEncodingConfig

# Both names predate the unified prethermal-shadow API and intentionally refer
# to the same configuration class.
GlobalFloquetInputEncodingConfig = PrethermalInputEncodingConfig

__all__ = [
    "BackendLike",
    "BatchReservoirProtocol",
    "ChannelReservoirProtocol",
    "CircuitLike",
    "CircuitReservoirProtocol",
    "ConfigMapping",
    "Dataset",
    "DatasetProtocol",
    "DatasetSplit",
    "DatasetSplitProtocol",
    "DimensionModelProtocol",
    "DynamicsInferenceProtocol",
    "DynamicsLike",
    "DynamicsSpec",
    "DynamicsSpecProtocol",
    "Experiment",
    "ExperimentProtocol",
    "ExperimentResult",
    "ExperimentResultProtocol",
    "FeatureMatrix",
    "GlobalFloquetConfig",
    "GlobalFloquetInputEncodingConfig",
    "GlobalFloquetPartialShadowReservoir",
    "HamiltonianLike",
    "HamiltonianSpecProtocol",
    "IndexSequence",
    "InputEncodingSpec",
    "InputEncodingSpecProtocol",
    "InputSequence",
    "MemoryObservableReservoirProtocol",
    "MetricCallable",
    "ObservableSpec",
    "PartialShadowReadoutConfig",
    "PauliTermLike",
    "PresetRegistryProtocol",
    "PrethermalCircuitConfig",
    "PrethermalInputEncodingConfig",
    "PrethermalShadowDimensionModel",
    "QRCReservoirProtocol",
    "QiskitArtifactMap",
    "QiskitGlobalFloquetPartialShadowReservoir",
    "QiskitReservoirConfigProtocol",
    "QuantumCircuitProtocol",
    "ReadoutProtocol",
    "ReadoutResetConfig",
    "ReadoutSpec",
    "ReadoutSpecProtocol",
    "ReservoirBuilderProtocol",
    "ReservoirCompilerProtocol",
    "ReservoirFactoryProtocol",
    "ReservoirRunResult",
    "ReservoirSpec",
    "ReservoirSpecProtocol",
    "ReservoirStepResult",
    "Ridge",
    "RunFunctionProtocol",
    "SerializableSpecProtocol",
    "SparsePauliOpProtocol",
    "StatefulReservoirProtocol",
    "StepReservoirProtocol",
    "StreamingReservoirProtocol",
    "SupervisedDataBuilderProtocol",
    "Sweep",
    "SweepProtocol",
    "SweepResult",
    "SweepResultProtocol",
    "TargetArray",
    "TaskDatasetFactoryProtocol",
    "TaskRunnerProtocol",
    "TimeSeriesDataBuilderProtocol",
    "TransformReservoirProtocol",
    "build_dimension_model",
    "build_hamiltonian_params",
    "build_qiskit_hamiltonian_artifacts",
    "compile_reservoir",
    "data",
    "presets",
    "qresreservoir",
    "readout",
    "run",
]
