"""Unified namespace for task-agnostic quantum reservoir computing tools."""

from .core.builders import build_dimension_model, build_hamiltonian_params, compile_reservoir, transform
from .core import (
    BackendLike,
    BatchReservoirProtocol,
    ChannelReservoirProtocol,
    CircuitReservoirProtocol,
    CircuitLike,
    ConfigMapping,
    DatasetSplitProtocol,
    DatasetProtocol,
    DimensionModelProtocol,
    ExperimentResultProtocol,
    ExperimentProtocol,
    FeatureMatrix,
    HamiltonianLike,
    HamiltonianSpecProtocol,
    IndexSequence,
    InputSequence,
    MemoryObservableReservoirProtocol,
    MetricCallable,
    ObservableSpec,
    PauliTermLike,
    QRCReservoirProtocol,
    ReadoutSpecProtocol,
    ReadoutProtocol,
    ReservoirBuilderProtocol,
    ReservoirCompilerProtocol,
    ReservoirFactoryProtocol,
    ReservoirSpecProtocol,
    ReservoirRunResult,
    ReservoirStepResult,
    SerializableSpecProtocol,
    StatefulReservoirProtocol,
    StepReservoirProtocol,
    StreamingReservoirProtocol,
    SupervisedDataBuilderProtocol,
    SweepProtocol,
    SweepResultProtocol,
    TargetArray,
    TaskDatasetFactoryProtocol,
    TaskRunnerProtocol,
    TimeSeriesDataBuilderProtocol,
    TransformReservoirProtocol,
)
from .core.fluent import ReservoirBuilder, qresreservoir, reservoir
from .core.specs import ReadoutSpec, ReservoirSpec
from . import presets
from .experiments import data, readout
from .experiments.datasets import Dataset, DatasetSplit
from .experiments.readout import Ridge
from .experiments.runner import Experiment, ExperimentResult, Sweep, SweepResult

__all__ = [
    "BackendLike",
    "BatchReservoirProtocol",
    "ChannelReservoirProtocol",
    "ConfigMapping",
    "CircuitLike",
    "CircuitReservoirProtocol",
    "Dataset",
    "DatasetSplitProtocol",
    "DatasetProtocol",
    "DatasetSplit",
    "DimensionModelProtocol",
    "Experiment",
    "ExperimentResultProtocol",
    "ExperimentProtocol",
    "ExperimentResult",
    "FeatureMatrix",
    "HamiltonianLike",
    "HamiltonianSpecProtocol",
    "IndexSequence",
    "InputSequence",
    "MemoryObservableReservoirProtocol",
    "MetricCallable",
    "ObservableSpec",
    "PauliTermLike",
    "QRCReservoirProtocol",
    "ReadoutSpecProtocol",
    "ReadoutProtocol",
    "ReadoutSpec",
    "ReservoirRunResult",
    "ReservoirSpec",
    "ReservoirSpecProtocol",
    "ReservoirStepResult",
    "ReservoirBuilder",
    "ReservoirBuilderProtocol",
    "ReservoirCompilerProtocol",
    "ReservoirFactoryProtocol",
    "Ridge",
    "qresreservoir",
    "presets",
    "SerializableSpecProtocol",
    "StatefulReservoirProtocol",
    "StepReservoirProtocol",
    "StreamingReservoirProtocol",
    "SupervisedDataBuilderProtocol",
    "Sweep",
    "SweepProtocol",
    "SweepResult",
    "SweepResultProtocol",
    "TargetArray",
    "TaskDatasetFactoryProtocol",
    "TaskRunnerProtocol",
    "TimeSeriesDataBuilderProtocol",
    "TransformReservoirProtocol",
    "build_dimension_model",
    "build_hamiltonian_params",
    "compile_reservoir",
    "data",
    "readout",
    "reservoir",
    "transform",
]
